before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev


language: cpp
script:
        - qmake -qt=qt5 -v
        - qmake -qt=qt5
        - make
